### ISSUE TITLE
A way to change animation duration

### ISSUE THREAD

**Issue by IgorKrupenja** [escamoteur/super_tooltip#13]
I was wondering if it is possible to change animation duration? I.e. the duration between tapping the target widget and tooltip fading in completely.

Thanks!

**Comment by evandrmb** [comment]
Was about to try a PR about that😅. But from what I see this is allowed in the future new version, right @escamoteur ?

Both durations (fade in and out) are present in the constructor.

**Comment by escamoteur** [comment]
yep, I guess sometimes next week or so or over xmas

**Comment by escamoteur** [comment]
Sorry for the delay, I was just too busy. What do you think about the new API?

**Comment by sunnykinger** [comment]
So there is no way to customize animation duration for fade in and fade out?
