### ISSUE TITLE
Bug: the arrow moves after the popover is visible

### ISSUE THREAD

**Issue by zhanghuanchong** [escamoteur/super_tooltip#14]
The initial position of the arrow is correct, but it moves a little up soon. Please fix. Thanks!

**Comment by escamoteur** [comment]
can you please record a screencast of this? Firt time I hear about this

**Comment by zhanghuanchong** [comment]
@escamoteur 

Actually, I found that this happens only on flutter's dev channel. After switching back to the stable channel, it works. so this is a bug of flutter. Closing
