### ISSUE TITLE
็How to close tooltip programmatically?

### ISSUE THREAD

**Issue by petchgabriel** [escamoteur/super_tooltip#15]
Hi contributor,
Thanks for awesome plugin. I have a question. Is there anyway to close tooltip programmatically?

Thanks in advance.

**Comment by evandrmb** [comment]
Yes. You can call: .close();


Here's an example of mine:
` tooltip.show(context);
                Future.delayed(Duration(seconds: 5))
                    .then((_) => tooltip.close());`

I passed that code to my InkWell onTap.

**Comment by escamoteur** [comment]
Thanks for jumping in @evandrmb

**Comment by evandrmb** [comment]
@escamoteur  It's my honor being able to help.

@petchgabriel if my previous comment solve your doubt: please close the issue. If it doesn't how could I help? :)

**Comment by escamoteur** [comment]
@evandrmb If you want, have a look at the future version https://github.com/escamoteur/super_tooltip/tree/new_version
which uses a better way to define the target and uses a controller

**Comment by evandrmb** [comment]
@escamoteur I've just looked at it. I believe the addition of a controller is great. Will make users code cleaner since the SuperTooltip could be added directly in the build method without passing it to a variable. Congratulations!

**Comment by petchgabriel** [comment]
> @escamoteur It's my honor being able to help.
> 
> @petchgabriel if my previous comment solve your doubt: please close the issue. If it doesn't how could I help? :)

Hi @evandrmb thanks for your reply.

I think this is not work in my application. In my code I needed to close the tooltip whether link or button inside was clicked.

**Comment by petchgabriel** [comment]
> @evandrmb If you want, have a look at the future version https://github.com/escamoteur/super_tooltip/tree/new_version
> which uses a better way to define the target and uses a controller

Hello @escamoteur I will try this version and then get back to you.

Thank you.

**Comment by evandrmb** [comment]
> > @escamoteur It's my honor being able to help.
> > 
> > @petchgabriel if my previous comment solve your doubt: please close the issue. If it doesn't how could I help? :)
> 
> Hi @evandrmb thanks for your reply.
> 
> I think this is not work in my application. In my code I needed to close the tooltip whether link or button inside was clicked. 
> 

Could you provide some code?

**Comment by escamoteur** [comment]
@petchgabriel What do you think about the new API?

**Comment by evandrmb** [comment]
Hi @escamoteur, there's any deadline for the new version to be released? In a recent project of mine would be really helpful to use TooltipController.

**Comment by escamoteur** [comment]
I'm currently a bit short of time, would you like to help?

**Comment by evandrmb** [comment]
Hi, sorry for the delay. I also hand full, but how could I help?

**Comment by evandrmb** [comment]
As far as I know apart from API changes the main difference between the new version and master is Null Safety, isn't it?

**Comment by escamoteur** [comment]
mainly giving the code another close look as this version wasn't done by myself. And then the most important thing to adjust the docs to the new API

**Comment by escamoteur** [comment]
Yeah but the API change in that you define the target widget totally different than before is a major breaking change

**Comment by evandrmb** [comment]
Well, I will try this during my weekends. But tooltip uses overlays which is kind of my weak spot on Flutter. Anyway, I would be glad to help!

**Comment by escamoteur** [comment]
then it's a great opperotunity to learn more about Overlays :-D

**Comment by dhaval-k-simformsolutions** [comment]
@evandrmb  @escamoteur Is there any way using which tooltip automatically closes when the user push of pop to the new screen?
