### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by plumhly** [escamoteur/super_tooltip#23]
Can you  make the `dimensions`  attribute of  _ShapeOverlay and _BubbleShape as SuperTooltip parameter。not set const EdgeInsets.all(10.0)

**Comment by mrgnhnt96** [comment]
Hey @plumhly 

Is the issue that there is a set default dimension rather that the api is not public?
If the dimensions were set to `EdgeInsets.zero`, you would be able to set you own padding within the content. Would this solve your problem?
