### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by 0xNF** [escamoteur/super_tooltip#25]
The current license file says "MIT" but the actual text of the license file doesn't match the MIT license. This makes using the library a little troublesome in some applications. Would you be able to add a legit MIT license to the repo?

**Comment by escamoteur** [comment]
you mean because of the copyright notice? usage right is clearly MIT

**Comment by 0xNF** [comment]
Yes, and thank you for making it available under such a permissive license!

I'm just trying to make my company's legal department happy. 
Usually MIT licenses are formatted like that found at https://opensource.org/licenses/MIT, with headers, definitions, and standard legalese license-y stuff.

**Comment by mrgnhnt96** [comment]
Hey @0xNF 

Ill update the license in an upcoming release. Hope this hasn't given you much trouble!
