### ISSUE TITLE
BackdropFilter with tooltip

### ISSUE THREAD

**Issue by aytunch** [escamoteur/super_tooltip#27]
I want the tooltip container to have a frosted look. In the API we only have a `backgrounColor`. How can we make this possible?

**Comment by mrgnhnt96** [comment]
Hey @aytunch!

Thanks for the issue!
What is your goal as far as the frosted look goes? Are you wanting to still have the `touchThroughArea` available? Or are you trying to frost the whole background?

**Comment by aytunch** [comment]
Hi @mrgnhnt96 
I am aiming for a tooltip as seen from the attached image:
<img width="600" alt="Screen Shot 2021-07-17 at 15 52 18" src="https://user-images.githubusercontent.com/6442915/126037488-81fe3a46-e01d-41f0-bb7b-1f238a7c44a4.png">

**Comment by mrgnhnt96** [comment]
Okay great, Ill play around with it and see what I can do!
