### ISSUE TITLE
TextAlignment support?

### ISSUE THREAD

**Issue by adrianvintu** [escamoteur/super_tooltip#31]
Does this plugin support textAlignment, specifically Center?

**Comment by adrianvintu** [comment]
I am using the default material tooltip and it has the alignment "hardcoded" to left, afaik. I wish for a nicer tooltip that can center text.

![tooltip](https://user-images.githubusercontent.com/33379688/133905510-629f9542-6ba1-4a17-bb71-997a74cc02ae.jpg)

**Comment by bensonarafat** [comment]
@adrianvintu 
You can now update to v2. 
Just use the Text `textAlign` property
