### ISSUE TITLE
Cannot modify content padding.

### ISSUE THREAD

**Issue by igonzarec** [escamoteur/super_tooltip#33]
Hi! Thanks for the great package! Little issue here. I am not able to see an option to modify the padding/margin around the content of the tooltip. It seems that there is something like a default padding. Maybe I am missing something. Otherwise I would recommend to add a property to control it. Thank you in advance!
![Screen Shot 2021-10-19 at 18 27 01](https://user-images.githubusercontent.com/69485054/138004181-b78927d5-7941-426a-8077-f71b24a4da8d.png)

Code used:
```dart
SuperTooltip(
      popupDirection: TooltipDirection.down,
      content: Material(
          child: Text(
            "Lorem ipsum dolor sit amet, consetetur sadipscingelitr, "
                "sed diam nonumy eirmod tempor invidunt ut laboreet dolore magna aliquyam erat, "
                "sed diam voluptua. At vero eos et accusam et justoduo dolores et ea rebum. ",
            softWrap: true,
          )),
    );
```

Something like being able to set this value in the _BubbleShape class.

```dart
EdgeInsetsGeometry get dimensions => new EdgeInsets.all(10.0); //this value of ten
```

Let me see if I manage to find some time to propose a merge for this feature.

**Comment by SaelRomero** [comment]
x2

**Comment by mduccc** [comment]
@igonzarec @bensonarafat 

The issue has been resolved.
