### ISSUE TITLE
Looking for new maintainer for this package

### ISSUE THREAD

**Issue by escamoteur** [escamoteur/super_tooltip#39]
Hi, I don't have the time anymore to maintain this project. 
If you ware interested in taking over the maintenance, please add a comment

**Comment by gauravmehta13** [comment]
Would love to work on this

**Comment by gauravmehta13** [comment]
Also the added issues like interesting to solve

**Comment by Benpaul320** [comment]
Hi, this is Ben, I will love to be part of the maintenance of this package..
Thanks

**Comment by escamoteur** [comment]
Hi my friends,

I'm sorry for not replying earlier after asking on Twitter but unfortunately, my depression returned. It's important for me to know that someone takes over maintenance and takes it seriously because I know there are many people using this package.

Now to what is to do :-)

Actually, there is a new version already waiting for quite some time in this branch 

https://github.com/escamoteur/super_tooltip/tree/v2

It uses a better way to select the target than how it is done today. 
It should be reviewed and the readme updated to explain the new version.

I will add you to the maintainers but will for the moment keep the repository owner. As soon as I see that someone is taking responsibility I will hand over control completely

thanks a lot for your help

**Comment by jonaspoxleitner** [comment]
Hi, we already wrote an Twitter and I would also be happy to help maintaining this package.

**Comment by Benpaul320** [comment]
Hi,
Thanks, just accepted your invitation. 
I will do my very best

**Comment by escamoteur** [comment]
Hi I just want to bring up the question if we should spend much time one the current version or if we shouldn't move on the the new one.
Would like your opinions

**Comment by Benpaul320** [comment]
Hi, My opinion is that we can move next version. I can move along from there.. 
Well, some ideas i have we can have some material rounded edges. 

And secondly, I spotted some issues.. it will be nice working on them too. 
Thanks

**Comment by realArafatBen** [comment]
Hi @escamoteur sorry about that 
Hope you are feeling much better now!! 

Yeah, I have been working on something for some time now, studying what you have done on the previous version and the same time working on my skills too.

**Comment by escamoteur** [comment]
ok, so what would be your next step?

**Comment by EArminjon** [comment]
Could you put many maintainer ? Many PR are waiting and some are very awaited.
