### ISSUE TITLE
tooltips shows at center arrowTipDistance no effect

### ISSUE THREAD

**Issue by walidbou6** [escamoteur/super_tooltip#48]
the tooltip is showing at the centre of the screen no effect when using `arrowTipDistance`; to put you in the context I have selectable text with other options when user select a word can click on a button to show some information about the selected word, the tooltips are showing far away from the selected word and stack the screen centre.
![tmp](https://user-images.githubusercontent.com/97338486/191352040-c96afc7b-c543-496b-a02e-ce7025e3c96d.jpg)

**Comment by bensonarafat** [comment]
Hi @walidbou6 
You can update to v2. 
this have been fixed
