### ISSUE TITLE
Release new version on pub.dev

### ISSUE THREAD

**Issue by mduccc** [escamoteur/super_tooltip#52]
Recently, I noticed that some pull requests have been merged. 

However, the [version](https://pub.dev/packages/super_tooltip) on pub.dev is still outdated, dating back to two years ago. 
I believe it is necessary to release a new version that includes the newly merged code.

**Comment by mduccc** [comment]
@bensonarafat

**Comment by mduccc** [comment]
I saw step Dart setup, but do not Flutter setup.

<img width="912" alt="image" src="https://github.com/escamoteur/super_tooltip/assets/18674411/3a3a6e4d-ba51-4c6b-9fd6-9dbd78140b94">

**Comment by mduccc** [comment]
Can you check the issue? 
@bensonarafat

**Comment by bensonarafat** [comment]
Fixed.
Any ways am working on releasing v2. 
will be out soon

**Comment by bensonarafat** [comment]
am closing this
