### ISSUE TITLE
Change default bool _isVisible = true to false

### ISSUE THREAD

**Issue by wxyash** [escamoteur/super_tooltip#61]
Hello, my request is to  change (super_tooltip_controller.dart: 9)

`
 bool _isVisible = true;
`

to

`
 bool _isVisible = false;
`

Reason:
By default the value should be false since it isn't visible right?
I also have some dependencies that checks on page load if the tooltip is open or not, and since the default is true, it always seems to think its open.

At present, I'm mitigating it by doing this at initState
`await tooltipController.hideTooltip();`

**Comment by bensonarafat** [comment]
Hi, @wxyash 
Thanks for your request. If it's okay by you. You could send a PR. I will preview and merge. 
Thanks

**Comment by JustinPriday** [comment]
Hi @bensonarafat. 

I Created a PR for this.
